require 'Items/ProceduralDistributions'

local function addItemToDist(category, item, chance)
    table.insert(ProceduralDistributions.list[category].items, item)
    table.insert(ProceduralDistributions.list[category].items, chance)
end

local function addRecorder(category, chance)
    addItemToDist(category, "ACRecorder", chance)
end

local function addTape(category, chance)
    addItemToDist(category, "ACRecorderTape", chance)
end

addRecorder("BreakRoomShelves", 0.125)
addRecorder("ClassroomShelves", 0.125)
addRecorder("MusicStoreOthers", 1)
addRecorder("MusicStoreCDs", 0.125)
addRecorder("MusicStoreSpeaker", 2.5)
addRecorder("CrateElectronics", 0.125)
addRecorder("ElectronicStoreMisc", 1)
addRecorder("ElectronicStoreMusic", 1)
addRecorder("GigamartHouseElectronics", 1)
addRecorder("KitchenBook", 0.1)
addRecorder("KitchenRandom", 0.01)
addRecorder("LivingRoomShelf", 0.2)
addRecorder("GarageTools", 0.125)
addRecorder("GarageMechanics", 0.125)
addRecorder("GarageCarpentry", 0.125)
addRecorder("GarageMetalwork", 0.125)
addRecorder("LivingRoomShelfNoTapes", 0.125)
addRecorder("Locker", 0.125)
addRecorder("LockerClassy", 0.125)
addRecorder("SchoolLockers", 0.1)
addRecorder("MechanicShelfElectric", 0.2)
addRecorder("CrateCompactDiscs", 0.125)
addRecorder("DeskGeneric", 0.125)
addRecorder("ShelfGeneric", 0.125)
addRecorder("MusicStoreCases", 0.1)
addRecorder("StoreCounterCleaning", 0.125)

addTape("BandPracticeInstruments", 0.5)
addTape("BedroomDresser", 0.5)
addTape("BedroomSideTable", 0.5)
addTape("ClosetShelfGeneric", 0.5)
addTape("CrateCompactDiscs", 0.1)
addTape("CrateCompactDiscs", 0.5)
addTape("CrateRandomJunk", 0.5)
addTape("DeskGeneric", 0.5)
addTape("DresserGeneric", 0.5)
addTape("ElectronicStoreMusic", 0.05)
addTape("ElectronicStoreMusic", 0.5)
addTape("FactoryLockers", 0.5)
addTape("FireDeptLockers", 0.5)
addTape("FitnessTrainer", 0.5)
addTape("Gifts", 0.5)
addTape("GolfLockers", 0.5)
addTape("GymLockers", 0.5)
addTape("Hobbies", 0.5)
addTape("HolidayStuff", 0.5)
addTape("HospitalLockers", 0.5)
addTape("LivingRoomShelf", 0.5)
addTape("LivingRoomShelfNoTapes", 0.5)
addTape("LivingRoomSideTable", 0.5)
addTape("LivingRoomSideTableNoRemote", 0.5)
addTape("Locker", 0.5)
addTape("LockerClassy", 0.5)
addTape("SchoolLockers", 1.0)
addTape("MusicStoreCDs", 0.05)
addTape("MusicStoreCDs", 0.5)
addTape("MusicStoreSpeaker", 0.1)
addTape("MusicStoreSpeaker", 0.5)
addTape("OfficeDesk", 0.5)
addTape("OfficeDeskHome", 0.5)
addTape("OfficeDrawers", 0.5)
addTape("PoliceDesk", 0.5)
addTape("PoliceLockers", 1.0)
addTape("SchoolLockers", 0.5)
addTape("SecurityLockers", 0.5)
addTape("ShelfGeneric", 0.5)
addTape("WardrobeChild", 0.5)
addTape("WardrobeMan", 0.5)
addTape("WardrobeManClassy", 0.5)
addTape("WardrobeRedneck", 0.5)
addTape("WardrobeWoman", 0.5)
addTape("WardrobeWomanClassy", 0.5)
